### PR TITLE
Add support for global elements

### PR DESCRIPTION
**Pull request by strategio**
https://onthegosystems.myjetbrains.com/youtrack/issue/wpmlcore-5375

### CODE REVIEW

**Comment by andreasciamanna** [comment]
@strategio as you can see in this PR, you are getting a bunch of inspection issues from Scrutinizer.

Can you please fix them before we start a review?

**Comment by strategio** [comment]
Sure @andreasciamanna, I will (I didn't notice because all checks are ticked).

**Comment by strategio** [comment]
@andreasciamanna I corrected the formatting issue reported by Scrutinizer except the doc comments, you can start the review!

**Comment by strategio** [comment]
Closing as we decided to handle it in Core directly.

**Pull request closed without merging**
